In [4]:
# Ans 1  : 

import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)

print("data type of array_list: ",type(array_list))

print("data type of list_: ",type(list_))

"""
Data type of list_ is type list 

and the data type of array_list is array of numpy

"""

data type of array_list:  <class 'numpy.ndarray'>
data type of list_:  <class 'list'>


In [5]:
# Ans 2 : 
print("type of list_ items")
for i in list_:
    print(type (i))
print("type of array_list items")

for j in array_list: 
    print(type(j))

type of list_ items
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
type of array_list items
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [7]:
# Ans 3 : 
array_list = np.array(object = list_, dtype = int)
for i in list_:
    print(type (i))
print("type of array_list items")

for j in array_list: 
    print(type(j))
    
"""
The date type has been converted in to int while converting the items into array of numpy type due to decleration of 
dtype in the np.array 

"""

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
type of array_list items
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [10]:
#Ans 4 : 
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

print("Shape of array :",num_array.shape)
print ("Size of array :", num_array.size)

Shape of array : (2, 3)
Size of array : 6


In [12]:
#Ans 5 : Create numpy array of 3*3 matrix containing zeros only

num_zero = np.zeros((3,3))
print(num_zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
#Ans 6 : Identity matrix of shape (5,5)
identity_mat = np.eye((5))
print(identity_mat)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
